name: Keep Servers Alive
on:
  schedule:
   - cron: '0 12 */10 * *' # Executes once every 10 days at 12:00 (private database has 500 minutes of runtime per month, 16 minutes per day).
  workflow_dispatch: 

jobs:
  keep_servers_alive:
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: >
        [
        { "SSH_USER":"Username", "SSH_PASS":"Password", "HOST":"Login IP or domain name", "PORT":"Port"}
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - name: Process each account
        run: |
             echo "*****************************************************"
             echo "*****************************************************"
             echo "Yongge's GitHub project: github.com/yonggekkk
             echo "Yongge's Blogger Blog: ygkkk.blogspot.com"
             echo Yongge's YouTube channel: www.youtube.com/@ygkkk
             echo "SSH script for remote login to a VPS server [Github]"
             echo "*****************************************************"
             echo "*****************************************************"
              count=0  
             for account in $(echo "${ACCOUNTS}" | jq -c '.[]'); do
              count=$((count+1))
              SSH_USER=$(echo $account | jq -r '.SSH_USER')
              SSH_PASS=$(echo $account | jq -r '.SSH_PASS')
              HOST=$(echo $account | jq -r '.HOST')
              PORT=$(echo $account | jq -r '.PORT')
             if sshpass -p "$SSH_PASS" ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$HOST" -q exit; then
             echo "🎉Congratulations! ✅The [$count]th server has successfully connected! 🚀Server address: $HOST, Username: $SSH_USER"
             else
             echo "💥Disaster! ❌Connection failed for the [$count]th server! 🚀Server address: $HOST, Username: $SSH_USER"
             fi
             sleep 5
             done
